type ScoreItem = {
  name: string;
  point: number;
};

const groupScore: ScoreItem[] = [
  { name: "First", point: 10 },
  { name: "Second", point: 5 },
  { name: "Third", point: 3 },
];

const individualScore: ScoreItem[] = [
  { name: "First", point: 5 },
  { name: "Second", point: 3 },
  { name: "Third", point: 1 },
];

export const teamData = [
  { name: "പഞ്ചവാദ്യം", link: "panchavadyam" },
  { name: "പടയണി", link: "padayani" },
  { name: "തെയ്യം", link: "theyyam" },
  { name: "കുമ്മാട്ടി", link: "kummati" },
];

export const departmentData = [
  { name: "BCA" },
  { name: "Psychology" },
  { name: "Political Science" },
  { name: "English" },
  { name: "History" },
  { name: "Economics" },
  { name: "Maths" },
  { name: "MSW" },
  { name: "M.com" },
  { name: "MA English" },
  { name: "BSW" },
  { name: "BBA" },
  { name: "B.com Finance" },
  { name: "B.com CA" },
  { name: "B.com Co-operation" },
];

export const itemsData = [
  { name: "Oppana", prize: groupScore },
  { name: "Dance", prize: groupScore },
  { name: "DuffMutt", prize: groupScore },
  { name: "Kathakali", prize: individualScore },
  { name: "Light Music(Male)", prize: individualScore },
  { name: "Light Music(Female)", prize: individualScore },
  { name: "Classical Music (Male)", prize: individualScore },
  { name: "Classical Music (Female)", prize: individualScore },
  { name: "Classical Dance", prize: individualScore },
  { name: "Mappilappattu(Male)", prize: individualScore },
  { name: "Mappilappattu(Female)", prize: individualScore },
  { name: "Kavitha parayanam", prize: individualScore },
  { name: "Western Music", prize: individualScore },
  { name: "Bharathanatyam", prize: individualScore },
  { name: "Mono Act", prize: individualScore },
  { name: "Mimicry", prize: individualScore },
  { name: "Keralanadanam", prize: individualScore },
  { name: "Stringed insturment(Western)", prize: individualScore },
  { name: "Group Song (Indian)", prize: groupScore },
  { name: "Group Song (Western)", prize: groupScore },
  { name: "Mappilappattu(Group)", prize: groupScore },
  { name: "Mohiniyattam", prize: individualScore },
  { name: "Patriotic Song", prize: groupScore },
  { name: "Ganamela", prize: groupScore },
  { name: "Kolkkali ", prize: groupScore },
  { name: "Vattapattu", prize: groupScore },
  { name: "Margamkali", prize: groupScore },
  { name: "Folk Dance(Male)", prize: individualScore },
  { name: "Folk Dance(Female)", prize: individualScore }, 
  { name: "Folk Dance(Group Male)", prize: groupScore },
  { name: "Folk Dance(Group Female)", prize: groupScore },
  { name: "Drama(Malayalam)", prize: groupScore },
  { name: "Drama(English)", prize: groupScore },
  { name: "Drama(Sanskrit)", prize: groupScore },
  { name: "Drama(Hindi)", prize: groupScore },
  { name: "Mime", prize: groupScore },
  { name: "Skit", prize: groupScore },
  { name: "Arabana", prize: groupScore },
  { name: "Painting(WaterColor)", prize: individualScore },
  { name: "Painting(OilColor)", prize: individualScore },
  { name: "Folk Song", prize: groupScore },
  { name: "Thiruvathira", prize: groupScore },
  { name: "Pencil Drawing", prize: individualScore },
  { name: "Cartoon Drawing", prize: individualScore },
  { name: "Rangoli", prize: individualScore },
  { name: "Collage", prize: individualScore },
  { name: "Photography", prize: individualScore },
  { name: "Clay Modelling", prize: individualScore },
  { name: "Embroidery", prize: individualScore },
  { name: "Poster Making", prize: individualScore },
  { name: "Essay Writing (Malayalam)", prize: individualScore },
  { name: "Essay Writing (English)", prize: individualScore },
  { name: "Essay Writing (Sanskrit)", prize: individualScore },
  { name: "Essay Writing (Hindi)", prize: individualScore },
  { name: "Essay Writing (Arabic)", prize: individualScore },
  { name: "Essay Writing (Urdu)", prize: individualScore },
  { name: "Essay Writing (Tamil)", prize: individualScore },
  { name: "Short Story Writing (Malayalam)", prize: individualScore },
  { name: "Short Story Writing (English)", prize: individualScore },
  { name: "Short Story Writing (Sanskrit)", prize: individualScore },
  { name: "Short Story Writing (Hindi)", prize: individualScore },
  { name: "Short Story Writing (Arabic)", prize: individualScore },
  { name: "Short Story Writing (Urdu)", prize: individualScore },
  { name: "Short Story Writing (Tamil)", prize: individualScore },
  { name: "Poem Versification (Malayalam)", prize: individualScore },
  { name: "Poem Versification (English)", prize: individualScore },
  { name: "Poem Versification (Sanskrit)", prize: individualScore },
  { name: "Poem Versification (Hindi)", prize: individualScore },
  { name: "Poem Versification (Arabic)", prize: individualScore },
  { name: "Poem Versification (Urdu)", prize: individualScore },
  { name: "Poem Versification (Tamil)", prize: individualScore },
  { name: "Elocution(Malayalam)", prize: individualScore },
  { name: "Elocution(English)", prize: individualScore },
  { name: "Elocution(Sanskrit)", prize: individualScore },
  { name: "Elocution(Hindi)", prize: individualScore },
  { name: "Elocution(Arabic)", prize: individualScore },
  { name: "Elocution(Urdu)", prize: individualScore },
  { name: "Elocution(Tamil)", prize: individualScore },
  { name: "Quiz", prize: groupScore },
  { name: "Debate", prize: groupScore },
  { name: "Kadhaprasangam", prize: individualScore },
];

export const prizeData = [
  { name: "First" },
  { name: "Second" },
  { name: "Third" },
];
